<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIuf8jdb\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIuf8jdb/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIuf8jdb.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIuf8jdb\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIuf8jdb\appProdProjectContainer([
    'container.build_hash' => 'Iuf8jdb',
    'container.build_id' => 'e8739644',
    'container.build_time' => 1564184451,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIuf8jdb');
